name: build-main
run-name: build-main
on:
  push:
    branches:
      - main
  schedule:
    # every day at midnight
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: download and save data
    steps:
      - uses: actions/checkout@v3

      # - run: bash main.sh

      # - run: curl --output osmconvert http://m.m.i24.cc/osmconvert64

      # - run: chmod +x ./osmconvert

      # - run: ./osmconvert --help

      # - run: ./osmconvert chattanooga.xml -o=chattanooga.pbf

      # - run: curl --output us-south-latest.osm.pbf https://download.geofabrik.de/north-america/us-south-latest.osm.pbf

      - run: curl --output tennessee-latest.osm.pbf https://download.geofabrik.de/north-america/us/tennessee-latest.osm.pbf

      - uses: systemed/tilemaker@v2.0.0
        with:
          input: ./tennessee-latest.osm.pbf
          output: ./tennessee-latest.pmtiles
          # config: ./chattanooga-config.json
          # Optional, same to --process
          # If not being set, default to resources/process-openmaptiles.lua
          # process: /path/to/lua
          # Optional, other arguments
          # If not being set, default to '--verbose'
          # extra: --threads 0
          # extra: --bbox='-86.98844491281493,34.014883133571566,-82.9877549774713,36.99317452988294'

      # - run: bash main.sh

      - run: ls

      - run: rm ./tennessee-latest.osm.pbf

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
